#############################################################################
# Makefile for building: subdir
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  subdir.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile subdir.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-src-QtStdDlgs \
		sub-src-QtProgressBar \
		sub-src-QtClock \
		sub-src-QtExtDlg \
		sub-src-QtGeometryDlg \
		sub-src-QtImageView \
		sub-src-QtImageView \
		sub-src-QtPalette \
		sub-src-QtShapeWidget \
		sub-src-QtSplashWindow \
		sub-src-QtWordProcessor \
		sub-src-Paint \
		sub-src-Draw \
		sub-src-Qt5DemosDlg


sub-src-QtStdDlgs-qmake_all:  FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile
	cd src/QtStdDlgs/ && $(MAKE) -f Makefile qmake_all
sub-src-QtStdDlgs: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtStdDlgs-make_first: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtStdDlgs-all: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtStdDlgs-clean: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtStdDlgs-distclean: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtStdDlgs-install_subtargets: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtStdDlgs-uninstall_subtargets: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtProgressBar-qmake_all:  FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile
	cd src/QtProgressBar/ && $(MAKE) -f Makefile qmake_all
sub-src-QtProgressBar: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtProgressBar-make_first: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtProgressBar-all: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtProgressBar-clean: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtProgressBar-distclean: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtProgressBar-install_subtargets: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtProgressBar-uninstall_subtargets: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtClock-qmake_all:  FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile
	cd src/QtClock/ && $(MAKE) -f Makefile qmake_all
sub-src-QtClock: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtClock-make_first: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtClock-all: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtClock-clean: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtClock-distclean: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtClock-install_subtargets: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtClock-uninstall_subtargets: FORCE
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtExtDlg-qmake_all:  FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile
	cd src/QtExtDlg/ && $(MAKE) -f Makefile qmake_all
sub-src-QtExtDlg: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtExtDlg-make_first: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtExtDlg-all: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtExtDlg-clean: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtExtDlg-distclean: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtExtDlg-install_subtargets: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtExtDlg-uninstall_subtargets: FORCE
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtGeometryDlg-qmake_all:  FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile
	cd src/QtGeometryDlg/ && $(MAKE) -f Makefile qmake_all
sub-src-QtGeometryDlg: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtGeometryDlg-make_first: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtGeometryDlg-all: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtGeometryDlg-clean: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtGeometryDlg-distclean: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtGeometryDlg-install_subtargets: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtGeometryDlg-uninstall_subtargets: FORCE
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtImageView-qmake_all:  FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile
	cd src/QtImageView/ && $(MAKE) -f Makefile qmake_all
sub-src-QtImageView: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtImageView-make_first: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtImageView-all: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtImageView-clean: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtImageView-distclean: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtImageView-install_subtargets: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtImageView-uninstall_subtargets: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtImageView-qmake_all:  FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile
	cd src/QtImageView/ && $(MAKE) -f Makefile qmake_all
sub-src-QtImageView: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtImageView-make_first: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtImageView-all: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtImageView-clean: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtImageView-distclean: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtImageView-install_subtargets: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtImageView-uninstall_subtargets: FORCE
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtPalette-qmake_all:  FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile
	cd src/QtPalette/ && $(MAKE) -f Makefile qmake_all
sub-src-QtPalette: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtPalette-make_first: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtPalette-all: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtPalette-clean: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtPalette-distclean: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtPalette-install_subtargets: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtPalette-uninstall_subtargets: FORCE
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtShapeWidget-qmake_all:  FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile
	cd src/QtShapeWidget/ && $(MAKE) -f Makefile qmake_all
sub-src-QtShapeWidget: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtShapeWidget-make_first: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtShapeWidget-all: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtShapeWidget-clean: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtShapeWidget-distclean: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtShapeWidget-install_subtargets: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtShapeWidget-uninstall_subtargets: FORCE
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtSplashWindow-qmake_all:  FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile
	cd src/QtSplashWindow/ && $(MAKE) -f Makefile qmake_all
sub-src-QtSplashWindow: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtSplashWindow-make_first: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtSplashWindow-all: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtSplashWindow-clean: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtSplashWindow-distclean: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtSplashWindow-install_subtargets: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtSplashWindow-uninstall_subtargets: FORCE
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtWordProcessor-qmake_all:  FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile
	cd src/QtWordProcessor/ && $(MAKE) -f Makefile qmake_all
sub-src-QtWordProcessor: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtWordProcessor-make_first: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtWordProcessor-all: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtWordProcessor-clean: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtWordProcessor-distclean: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtWordProcessor-install_subtargets: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtWordProcessor-uninstall_subtargets: FORCE
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-Paint-qmake_all:  FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile
	cd src/Paint/ && $(MAKE) -f Makefile qmake_all
sub-src-Paint: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-Paint-make_first: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-Paint-all: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-Paint-clean: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-Paint-distclean: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-Paint-install_subtargets: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-Paint-uninstall_subtargets: FORCE
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-Draw-qmake_all:  FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile
	cd src/Draw/ && $(MAKE) -f Makefile qmake_all
sub-src-Draw: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-Draw-make_first: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-Draw-all: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-Draw-clean: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-Draw-distclean: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-Draw-install_subtargets: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-Draw-uninstall_subtargets: FORCE
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-Qt5DemosDlg-qmake_all:  FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile
	cd src/Qt5DemosDlg/ && $(MAKE) -f Makefile qmake_all
sub-src-Qt5DemosDlg: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-Qt5DemosDlg-make_first: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-Qt5DemosDlg-all: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-Qt5DemosDlg-clean: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-Qt5DemosDlg-distclean: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-Qt5DemosDlg-install_subtargets: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-Qt5DemosDlg-uninstall_subtargets: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: subdir.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		subdir.pro
	$(QMAKE) -o Makefile subdir.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
subdir.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile subdir.pro

qmake_all: sub-src-QtStdDlgs-qmake_all sub-src-QtProgressBar-qmake_all sub-src-QtClock-qmake_all sub-src-QtExtDlg-qmake_all sub-src-QtGeometryDlg-qmake_all sub-src-QtImageView-qmake_all sub-src-QtImageView-qmake_all sub-src-QtPalette-qmake_all sub-src-QtShapeWidget-qmake_all sub-src-QtSplashWindow-qmake_all sub-src-QtWordProcessor-qmake_all sub-src-Paint-qmake_all sub-src-Draw-qmake_all sub-src-Qt5DemosDlg-qmake_all FORCE

make_first: sub-src-QtStdDlgs-make_first sub-src-QtProgressBar-make_first sub-src-QtClock-make_first sub-src-QtExtDlg-make_first sub-src-QtGeometryDlg-make_first sub-src-QtImageView-make_first sub-src-QtImageView-make_first sub-src-QtPalette-make_first sub-src-QtShapeWidget-make_first sub-src-QtSplashWindow-make_first sub-src-QtWordProcessor-make_first sub-src-Paint-make_first sub-src-Draw-make_first sub-src-Qt5DemosDlg-make_first FORCE
all: sub-src-QtStdDlgs-all sub-src-QtProgressBar-all sub-src-QtClock-all sub-src-QtExtDlg-all sub-src-QtGeometryDlg-all sub-src-QtImageView-all sub-src-QtImageView-all sub-src-QtPalette-all sub-src-QtShapeWidget-all sub-src-QtSplashWindow-all sub-src-QtWordProcessor-all sub-src-Paint-all sub-src-Draw-all sub-src-Qt5DemosDlg-all FORCE
clean: sub-src-QtStdDlgs-clean sub-src-QtProgressBar-clean sub-src-QtClock-clean sub-src-QtExtDlg-clean sub-src-QtGeometryDlg-clean sub-src-QtImageView-clean sub-src-QtImageView-clean sub-src-QtPalette-clean sub-src-QtShapeWidget-clean sub-src-QtSplashWindow-clean sub-src-QtWordProcessor-clean sub-src-Paint-clean sub-src-Draw-clean sub-src-Qt5DemosDlg-clean FORCE
distclean: sub-src-QtStdDlgs-distclean sub-src-QtProgressBar-distclean sub-src-QtClock-distclean sub-src-QtExtDlg-distclean sub-src-QtGeometryDlg-distclean sub-src-QtImageView-distclean sub-src-QtImageView-distclean sub-src-QtPalette-distclean sub-src-QtShapeWidget-distclean sub-src-QtSplashWindow-distclean sub-src-QtWordProcessor-distclean sub-src-Paint-distclean sub-src-Draw-distclean sub-src-Qt5DemosDlg-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-QtStdDlgs-install_subtargets sub-src-QtProgressBar-install_subtargets sub-src-QtClock-install_subtargets sub-src-QtExtDlg-install_subtargets sub-src-QtGeometryDlg-install_subtargets sub-src-QtImageView-install_subtargets sub-src-QtImageView-install_subtargets sub-src-QtPalette-install_subtargets sub-src-QtShapeWidget-install_subtargets sub-src-QtSplashWindow-install_subtargets sub-src-QtWordProcessor-install_subtargets sub-src-Paint-install_subtargets sub-src-Draw-install_subtargets sub-src-Qt5DemosDlg-install_subtargets FORCE
uninstall_subtargets: sub-src-QtStdDlgs-uninstall_subtargets sub-src-QtProgressBar-uninstall_subtargets sub-src-QtClock-uninstall_subtargets sub-src-QtExtDlg-uninstall_subtargets sub-src-QtGeometryDlg-uninstall_subtargets sub-src-QtImageView-uninstall_subtargets sub-src-QtImageView-uninstall_subtargets sub-src-QtPalette-uninstall_subtargets sub-src-QtShapeWidget-uninstall_subtargets sub-src-QtSplashWindow-uninstall_subtargets sub-src-QtWordProcessor-uninstall_subtargets sub-src-Paint-uninstall_subtargets sub-src-Draw-uninstall_subtargets sub-src-Qt5DemosDlg-uninstall_subtargets FORCE

sub-src-QtStdDlgs-check:
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtProgressBar-check:
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtClock-check:
	@test -d src/QtClock/ || mkdir -p src/QtClock/
	cd src/QtClock/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtClock/QtClock.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtExtDlg-check:
	@test -d src/QtExtDlg/ || mkdir -p src/QtExtDlg/
	cd src/QtExtDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtExtDlg/QtExtDlg.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtGeometryDlg-check:
	@test -d src/QtGeometryDlg/ || mkdir -p src/QtGeometryDlg/
	cd src/QtGeometryDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtGeometryDlg/QtGeometryDlg.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtImageView-check:
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtImageView-check:
	@test -d src/QtImageView/ || mkdir -p src/QtImageView/
	cd src/QtImageView/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtImageView/QtImageView.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtPalette-check:
	@test -d src/QtPalette/ || mkdir -p src/QtPalette/
	cd src/QtPalette/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtPalette/QtPalette.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtShapeWidget-check:
	@test -d src/QtShapeWidget/ || mkdir -p src/QtShapeWidget/
	cd src/QtShapeWidget/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtShapeWidget/QtShapeWidget.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtSplashWindow-check:
	@test -d src/QtSplashWindow/ || mkdir -p src/QtSplashWindow/
	cd src/QtSplashWindow/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtSplashWindow/QtSplashWindow.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtWordProcessor-check:
	@test -d src/QtWordProcessor/ || mkdir -p src/QtWordProcessor/
	cd src/QtWordProcessor/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtWordProcessor/QtWordProcessor.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-Paint-check:
	@test -d src/Paint/ || mkdir -p src/Paint/
	cd src/Paint/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Paint/Paint.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-Draw-check:
	@test -d src/Draw/ || mkdir -p src/Draw/
	cd src/Draw/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Draw/Draw.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-Qt5DemosDlg-check:
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-QtStdDlgs-check sub-src-QtProgressBar-check sub-src-QtClock-check sub-src-QtExtDlg-check sub-src-QtGeometryDlg-check sub-src-QtImageView-check sub-src-QtImageView-check sub-src-QtPalette-check sub-src-QtShapeWidget-check sub-src-QtSplashWindow-check sub-src-QtWordProcessor-check sub-src-Paint-check sub-src-Draw-check sub-src-Qt5DemosDlg-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

