#############################################################################
# Makefile for building: subdir
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  subdir.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile subdir.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-src-QtStdDlgs \
		sub-src-QtProgressBar \
		sub-src-Qt5DemosDlg


sub-src-QtStdDlgs-qmake_all:  FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile
	cd src/QtStdDlgs/ && $(MAKE) -f Makefile qmake_all
sub-src-QtStdDlgs: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtStdDlgs-make_first: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtStdDlgs-all: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtStdDlgs-clean: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtStdDlgs-distclean: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtStdDlgs-install_subtargets: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtStdDlgs-uninstall_subtargets: FORCE
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-QtProgressBar-qmake_all:  FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile
	cd src/QtProgressBar/ && $(MAKE) -f Makefile qmake_all
sub-src-QtProgressBar: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-QtProgressBar-make_first: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-QtProgressBar-all: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-QtProgressBar-clean: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-QtProgressBar-distclean: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-QtProgressBar-install_subtargets: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-QtProgressBar-uninstall_subtargets: FORCE
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-Qt5DemosDlg-qmake_all:  FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile
	cd src/Qt5DemosDlg/ && $(MAKE) -f Makefile qmake_all
sub-src-Qt5DemosDlg: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-Qt5DemosDlg-make_first: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-Qt5DemosDlg-all: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-Qt5DemosDlg-clean: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-Qt5DemosDlg-distclean: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-Qt5DemosDlg-install_subtargets: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-Qt5DemosDlg-uninstall_subtargets: FORCE
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: subdir.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		subdir.pro
	$(QMAKE) -o Makefile subdir.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
subdir.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile subdir.pro

qmake_all: sub-src-QtStdDlgs-qmake_all sub-src-QtProgressBar-qmake_all sub-src-Qt5DemosDlg-qmake_all FORCE

make_first: sub-src-QtStdDlgs-make_first sub-src-QtProgressBar-make_first sub-src-Qt5DemosDlg-make_first FORCE
all: sub-src-QtStdDlgs-all sub-src-QtProgressBar-all sub-src-Qt5DemosDlg-all FORCE
clean: sub-src-QtStdDlgs-clean sub-src-QtProgressBar-clean sub-src-Qt5DemosDlg-clean FORCE
distclean: sub-src-QtStdDlgs-distclean sub-src-QtProgressBar-distclean sub-src-Qt5DemosDlg-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-QtStdDlgs-install_subtargets sub-src-QtProgressBar-install_subtargets sub-src-Qt5DemosDlg-install_subtargets FORCE
uninstall_subtargets: sub-src-QtStdDlgs-uninstall_subtargets sub-src-QtProgressBar-uninstall_subtargets sub-src-Qt5DemosDlg-uninstall_subtargets FORCE

sub-src-QtStdDlgs-check:
	@test -d src/QtStdDlgs/ || mkdir -p src/QtStdDlgs/
	cd src/QtStdDlgs/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtStdDlgs/QtStdDlgs.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-QtProgressBar-check:
	@test -d src/QtProgressBar/ || mkdir -p src/QtProgressBar/
	cd src/QtProgressBar/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/QtProgressBar/QtProgressBar.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-src-Qt5DemosDlg-check:
	@test -d src/Qt5DemosDlg/ || mkdir -p src/Qt5DemosDlg/
	cd src/Qt5DemosDlg/ && ( test -e Makefile || $(QMAKE) /home/jisiyu/src/Qt/Qt5DemosDir/src/Qt5DemosDlg/Qt5DemosDlg.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-QtStdDlgs-check sub-src-QtProgressBar-check sub-src-Qt5DemosDlg-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

