######################################################################
# Automatically generated by qmake (3.0) ?? 6? 18 14:00:55 2016
######################################################################

TEMPLATE = lib
TARGET = QtSplashWindow
DESTDIR = ../../build/lib
INCLUDEPATH += .
CONFIG += c++11
CONFIG += qt
QT += core gui widgets

HEADERS += QtSplashWindow.h

SOURCES += QtSplashWindow.cpp

# Directories
