######################################################################
# Automatically generated by qmake (3.0) ?? 6? 18 08:07:04 2016
######################################################################

TEMPLATE = lib
TARGET = QtClock
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .
CONFIG += c++11
CONFIG += qt
QT += core gui widgets

HEADERS += QtClock.h

SOURCES += QtClock.cpp


# Directories
