######################################################################
# Automatically generated by qmake (3.0) ?? 7? 8 16:02:48 2016
######################################################################

TEMPLATE = lib
TARGET = QtGeometryDlg
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .
CONFIG += qt
CONFIG += c++11
QT += gui core widgets

SOURCES += QtGeometryDlg.cpp

HEADERS += QtGeometryDlg.h

# Directories
