######################################################################
# Automatically generated by qmake (3.0) ?? 6? 18 14:44:31 2016
######################################################################

TEMPLATE = lib
TARGET = QtMainWindow
DESTDIR = ../../build/lib
INCLUDEPATH += .
CONFIG += qt
CONFIG += c++11
QT += core gui widgets
QT += printsupport

HEADERS += QtWordProcessor.h

SOURCES +=	QtWordProcessor.cpp

RESOURCES += icon.qrc

# Directories
