######################################################################
# Automatically generated by qmake (3.0) ?? 6? 18 10:33:40 2016
######################################################################

TEMPLATE = lib
TARGET = QtExtDlg
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .
CONFIG += c++11
CONFIG += qt
CONFIG += c++11
QT += core gui widgets

HEADERS += QtExtDlg.h

SOURCES += QtExtDlg.cpp


# Directories
