######################################################################
# Automatically generated by qmake (3.0) ?? 7? 8 23:12:50 2016
######################################################################

TEMPLATE = lib
TARGET = QtImageView
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .
CONFIG += c++11
CONFIG += qt
QT += core gui widgets

# Input
HEADERS += QtImageView.h
SOURCES += QtImageView.cpp
RESOURCES += icon.qrc
