######################################################################
# Automatically generated by qmake (3.0) ?? 6? 18 13:11:27 2016
######################################################################

TEMPLATE = lib
Target = QtShapeWidget
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .
CONFIG += c++11
CONFIG += qt
QT += core gui widgets

HEADERS += QtShapeWidget.h

SOURCES += QtShapeWidget.cpp

RESOURCES += image.qrc

# Directories
