######################################################################
# Automatically generated by qmake (3.0) ?? 6? 16 13:36:14 2016
######################################################################

TEMPLATE = lib
TARGET = QtPalette
DESTDIR = ../../build/lib
VERSION = 0.0.1
INCLUDEPATH += .

CONFIG += qt
CONFIG += c++11
QT += core gui widgets

HEADERS += QtPaletteDlg.h

SOURCES += QtPaletteDlg.cpp
